// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: health.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MethodHealthClient is the client API for MethodHealth service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MethodHealthClient interface {
	Check(ctx context.Context, in *MethodHealthRequest, opts ...grpc.CallOption) (*MethodHealthResponse, error)
}

type methodHealthClient struct {
	cc grpc.ClientConnInterface
}

func NewMethodHealthClient(cc grpc.ClientConnInterface) MethodHealthClient {
	return &methodHealthClient{cc}
}

func (c *methodHealthClient) Check(ctx context.Context, in *MethodHealthRequest, opts ...grpc.CallOption) (*MethodHealthResponse, error) {
	out := new(MethodHealthResponse)
	err := c.cc.Invoke(ctx, "/ankrscan.health.MethodHealth/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MethodHealthServer is the server API for MethodHealth service.
// All implementations must embed UnimplementedMethodHealthServer
// for forward compatibility
type MethodHealthServer interface {
	Check(context.Context, *MethodHealthRequest) (*MethodHealthResponse, error)
	mustEmbedUnimplementedMethodHealthServer()
}

// UnimplementedMethodHealthServer must be embedded to have forward compatible implementations.
type UnimplementedMethodHealthServer struct {
}

func (UnimplementedMethodHealthServer) Check(context.Context, *MethodHealthRequest) (*MethodHealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedMethodHealthServer) mustEmbedUnimplementedMethodHealthServer() {}

// UnsafeMethodHealthServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MethodHealthServer will
// result in compilation errors.
type UnsafeMethodHealthServer interface {
	mustEmbedUnimplementedMethodHealthServer()
}

func RegisterMethodHealthServer(s grpc.ServiceRegistrar, srv MethodHealthServer) {
	s.RegisterService(&MethodHealth_ServiceDesc, srv)
}

func _MethodHealth_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MethodHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MethodHealthServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ankrscan.health.MethodHealth/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MethodHealthServer).Check(ctx, req.(*MethodHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MethodHealth_ServiceDesc is the grpc.ServiceDesc for MethodHealth service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MethodHealth_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ankrscan.health.MethodHealth",
	HandlerType: (*MethodHealthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _MethodHealth_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
