// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// TokenIndexerClient is the client API for TokenIndexer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenIndexerClient interface {
}

type tokenIndexerClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenIndexerClient(cc grpc.ClientConnInterface) TokenIndexerClient {
	return &tokenIndexerClient{cc}
}

// TokenIndexerServer is the server API for TokenIndexer service.
// All implementations must embed UnimplementedTokenIndexerServer
// for forward compatibility
type TokenIndexerServer interface {
	mustEmbedUnimplementedTokenIndexerServer()
}

// UnimplementedTokenIndexerServer must be embedded to have forward compatible implementations.
type UnimplementedTokenIndexerServer struct {
}

func (UnimplementedTokenIndexerServer) mustEmbedUnimplementedTokenIndexerServer() {}

// UnsafeTokenIndexerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenIndexerServer will
// result in compilation errors.
type UnsafeTokenIndexerServer interface {
	mustEmbedUnimplementedTokenIndexerServer()
}

func RegisterTokenIndexerServer(s grpc.ServiceRegistrar, srv TokenIndexerServer) {
	s.RegisterService(&TokenIndexer_ServiceDesc, srv)
}

// TokenIndexer_ServiceDesc is the grpc.ServiceDesc for TokenIndexer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenIndexer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ankrscan.tokenindexer.TokenIndexer",
	HandlerType: (*TokenIndexerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "token-indexer.proto",
}
