// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: blockchain-settings.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//*
//  _____       _   _ _   _
// | ____|_ __ | |_(_) |_(_) ___  ___
// |  _| | '_ \| __| | __| |/ _ \/ __|
// | |___| | | | |_| | |_| |  __/\__ \
// |_____|_| |_|\__|_|\__|_|\___||___/
//
type ChainType int32

const (
	ChainType_CHAIN_TYPE_ETHEREUM ChainType = 0
	ChainType_CHAIN_TYPE_POLKADOT ChainType = 1
)

// Enum value maps for ChainType.
var (
	ChainType_name = map[int32]string{
		0: "CHAIN_TYPE_ETHEREUM",
		1: "CHAIN_TYPE_POLKADOT",
	}
	ChainType_value = map[string]int32{
		"CHAIN_TYPE_ETHEREUM": 0,
		"CHAIN_TYPE_POLKADOT": 1,
	}
)

func (x ChainType) Enum() *ChainType {
	p := new(ChainType)
	*p = x
	return p
}

func (x ChainType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainType) Descriptor() protoreflect.EnumDescriptor {
	return file_blockchain_settings_proto_enumTypes[0].Descriptor()
}

func (ChainType) Type() protoreflect.EnumType {
	return &file_blockchain_settings_proto_enumTypes[0]
}

func (x ChainType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainType.Descriptor instead.
func (ChainType) EnumDescriptor() ([]byte, []int) {
	return file_blockchain_settings_proto_rawDescGZIP(), []int{0}
}

type BlockchainSettings struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockchainName   string    `protobuf:"bytes,1,opt,name=blockchain_name,json=blockchainName,proto3" json:"blockchain_name,omitempty"`
	VerboseName      string    `protobuf:"bytes,2,opt,name=verbose_name,json=verboseName,proto3" json:"verbose_name,omitempty"`
	KafkaBlocksTopic string    `protobuf:"bytes,3,opt,name=kafka_blocks_topic,json=kafkaBlocksTopic,proto3" json:"kafka_blocks_topic,omitempty"`
	ChainType        ChainType `protobuf:"varint,4,opt,name=chain_type,json=chainType,proto3,enum=com.ankrscan.blockchainsettings.ChainType" json:"chain_type,omitempty"`
	NodeUrl          string    `protobuf:"bytes,5,opt,name=node_url,json=nodeUrl,proto3" json:"node_url,omitempty"`
	Symbol           string    `protobuf:"bytes,6,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals         int64     `protobuf:"varint,7,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (x *BlockchainSettings) Reset() {
	*x = BlockchainSettings{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_settings_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlockchainSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockchainSettings) ProtoMessage() {}

func (x *BlockchainSettings) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_settings_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockchainSettings.ProtoReflect.Descriptor instead.
func (*BlockchainSettings) Descriptor() ([]byte, []int) {
	return file_blockchain_settings_proto_rawDescGZIP(), []int{0}
}

func (x *BlockchainSettings) GetBlockchainName() string {
	if x != nil {
		return x.BlockchainName
	}
	return ""
}

func (x *BlockchainSettings) GetVerboseName() string {
	if x != nil {
		return x.VerboseName
	}
	return ""
}

func (x *BlockchainSettings) GetKafkaBlocksTopic() string {
	if x != nil {
		return x.KafkaBlocksTopic
	}
	return ""
}

func (x *BlockchainSettings) GetChainType() ChainType {
	if x != nil {
		return x.ChainType
	}
	return ChainType_CHAIN_TYPE_ETHEREUM
}

func (x *BlockchainSettings) GetNodeUrl() string {
	if x != nil {
		return x.NodeUrl
	}
	return ""
}

func (x *BlockchainSettings) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BlockchainSettings) GetDecimals() int64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

//*
// Topic: v1.blockchainsettings.settingschanged
type SettingsChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Settings []*BlockchainSettings `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
}

func (x *SettingsChanged) Reset() {
	*x = SettingsChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blockchain_settings_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingsChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsChanged) ProtoMessage() {}

func (x *SettingsChanged) ProtoReflect() protoreflect.Message {
	mi := &file_blockchain_settings_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsChanged.ProtoReflect.Descriptor instead.
func (*SettingsChanged) Descriptor() ([]byte, []int) {
	return file_blockchain_settings_proto_rawDescGZIP(), []int{1}
}

func (x *SettingsChanged) GetSettings() []*BlockchainSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

var File_blockchain_settings_proto protoreflect.FileDescriptor

var file_blockchain_settings_proto_rawDesc = []byte{
	0x0a, 0x19, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2d, 0x73, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x63, 0x6f, 0x6d,
	0x2e, 0x61, 0x6e, 0x6b, 0x72, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x22, 0xa8, 0x02, 0x0a,
	0x12, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x62, 0x6c,
	0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c,
	0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x76, 0x65, 0x72, 0x62, 0x6f, 0x73, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x6b, 0x61, 0x66, 0x6b, 0x61, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x5f,
	0x74, 0x6f, 0x70, 0x69, 0x63, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6b, 0x61, 0x66,
	0x6b, 0x61, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x49, 0x0a,
	0x0a, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x2a, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x72, 0x73, 0x63, 0x61, 0x6e,
	0x2e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x63,
	0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6e, 0x6f, 0x64, 0x65,
	0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x22, 0x62, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x4f, 0x0a, 0x08, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x72, 0x73, 0x63, 0x61, 0x6e, 0x2e, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x52, 0x08, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2a, 0x3d, 0x0a, 0x09, 0x43,
	0x68, 0x61, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x48, 0x41, 0x49,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x45, 0x54, 0x48, 0x45, 0x52, 0x45, 0x55, 0x4d, 0x10,
	0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x50, 0x4f, 0x4c, 0x4b, 0x41, 0x44, 0x4f, 0x54, 0x10, 0x01, 0x42, 0x35, 0x0a, 0x10, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x6c, 0x6f, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x42, 0x17,
	0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_blockchain_settings_proto_rawDescOnce sync.Once
	file_blockchain_settings_proto_rawDescData = file_blockchain_settings_proto_rawDesc
)

func file_blockchain_settings_proto_rawDescGZIP() []byte {
	file_blockchain_settings_proto_rawDescOnce.Do(func() {
		file_blockchain_settings_proto_rawDescData = protoimpl.X.CompressGZIP(file_blockchain_settings_proto_rawDescData)
	})
	return file_blockchain_settings_proto_rawDescData
}

var file_blockchain_settings_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blockchain_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_blockchain_settings_proto_goTypes = []interface{}{
	(ChainType)(0),             // 0: com.ankrscan.blockchainsettings.ChainType
	(*BlockchainSettings)(nil), // 1: com.ankrscan.blockchainsettings.BlockchainSettings
	(*SettingsChanged)(nil),    // 2: com.ankrscan.blockchainsettings.SettingsChanged
}
var file_blockchain_settings_proto_depIdxs = []int32{
	0, // 0: com.ankrscan.blockchainsettings.BlockchainSettings.chain_type:type_name -> com.ankrscan.blockchainsettings.ChainType
	1, // 1: com.ankrscan.blockchainsettings.SettingsChanged.settings:type_name -> com.ankrscan.blockchainsettings.BlockchainSettings
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_blockchain_settings_proto_init() }
func file_blockchain_settings_proto_init() {
	if File_blockchain_settings_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_blockchain_settings_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlockchainSettings); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blockchain_settings_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettingsChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blockchain_settings_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blockchain_settings_proto_goTypes,
		DependencyIndexes: file_blockchain_settings_proto_depIdxs,
		EnumInfos:         file_blockchain_settings_proto_enumTypes,
		MessageInfos:      file_blockchain_settings_proto_msgTypes,
	}.Build()
	File_blockchain_settings_proto = out.File
	file_blockchain_settings_proto_rawDesc = nil
	file_blockchain_settings_proto_goTypes = nil
	file_blockchain_settings_proto_depIdxs = nil
}
