// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ExtractorClient is the client API for Extractor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ExtractorClient interface {
	GetLatestBalance(ctx context.Context, in *GetLatestBalanceRequest, opts ...grpc.CallOption) (*GetLatestBalanceReply, error)
	GetTransactionByHash(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*GetTransactionByHashReply, error)
	GetTransactionByHashFast(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*GetTransactionByHashReply, error)
	GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*GetBlockByHeightReply, error)
	GetBlockHeaderByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*GetBlockByHeightReply, error)
	// extractors configurations API
	GetExtractors(ctx context.Context, in *GetExtractorsRequest, opts ...grpc.CallOption) (*ExtractorConfigs, error)
	UpdateExtractors(ctx context.Context, in *UpdateExtractorsRequest, opts ...grpc.CallOption) (*ExtractorConfigs, error)
	DeleteExtractors(ctx context.Context, in *DeleteExtractorsRequest, opts ...grpc.CallOption) (*ExtractorConfigs, error)
	// consumer API
	NextBlocks(ctx context.Context, in *NextBlocksRequest, opts ...grpc.CallOption) (*NextBlocksReply, error)
	CommitBlock(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error)
	NewConsumer(ctx context.Context, in *NewConsumerRequest, opts ...grpc.CallOption) (*NewConsumerReply, error)
}

type extractorClient struct {
	cc grpc.ClientConnInterface
}

func NewExtractorClient(cc grpc.ClientConnInterface) ExtractorClient {
	return &extractorClient{cc}
}

func (c *extractorClient) GetLatestBalance(ctx context.Context, in *GetLatestBalanceRequest, opts ...grpc.CallOption) (*GetLatestBalanceReply, error) {
	out := new(GetLatestBalanceReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/GetLatestBalance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) GetTransactionByHash(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*GetTransactionByHashReply, error) {
	out := new(GetTransactionByHashReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/GetTransactionByHash", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) GetTransactionByHashFast(ctx context.Context, in *GetTransactionByHashRequest, opts ...grpc.CallOption) (*GetTransactionByHashReply, error) {
	out := new(GetTransactionByHashReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/GetTransactionByHashFast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) GetBlockByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*GetBlockByHeightReply, error) {
	out := new(GetBlockByHeightReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/GetBlockByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) GetBlockHeaderByHeight(ctx context.Context, in *GetBlockByHeightRequest, opts ...grpc.CallOption) (*GetBlockByHeightReply, error) {
	out := new(GetBlockByHeightReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/GetBlockHeaderByHeight", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) GetExtractors(ctx context.Context, in *GetExtractorsRequest, opts ...grpc.CallOption) (*ExtractorConfigs, error) {
	out := new(ExtractorConfigs)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/GetExtractors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) UpdateExtractors(ctx context.Context, in *UpdateExtractorsRequest, opts ...grpc.CallOption) (*ExtractorConfigs, error) {
	out := new(ExtractorConfigs)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/UpdateExtractors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) DeleteExtractors(ctx context.Context, in *DeleteExtractorsRequest, opts ...grpc.CallOption) (*ExtractorConfigs, error) {
	out := new(ExtractorConfigs)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/DeleteExtractors", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) NextBlocks(ctx context.Context, in *NextBlocksRequest, opts ...grpc.CallOption) (*NextBlocksReply, error) {
	out := new(NextBlocksReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/NextBlocks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) CommitBlock(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitReply, error) {
	out := new(CommitReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/CommitBlock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *extractorClient) NewConsumer(ctx context.Context, in *NewConsumerRequest, opts ...grpc.CallOption) (*NewConsumerReply, error) {
	out := new(NewConsumerReply)
	err := c.cc.Invoke(ctx, "/com.ankrscan.extractor.Extractor/NewConsumer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExtractorServer is the server API for Extractor service.
// All implementations must embed UnimplementedExtractorServer
// for forward compatibility
type ExtractorServer interface {
	GetLatestBalance(context.Context, *GetLatestBalanceRequest) (*GetLatestBalanceReply, error)
	GetTransactionByHash(context.Context, *GetTransactionByHashRequest) (*GetTransactionByHashReply, error)
	GetTransactionByHashFast(context.Context, *GetTransactionByHashRequest) (*GetTransactionByHashReply, error)
	GetBlockByHeight(context.Context, *GetBlockByHeightRequest) (*GetBlockByHeightReply, error)
	GetBlockHeaderByHeight(context.Context, *GetBlockByHeightRequest) (*GetBlockByHeightReply, error)
	// extractors configurations API
	GetExtractors(context.Context, *GetExtractorsRequest) (*ExtractorConfigs, error)
	UpdateExtractors(context.Context, *UpdateExtractorsRequest) (*ExtractorConfigs, error)
	DeleteExtractors(context.Context, *DeleteExtractorsRequest) (*ExtractorConfigs, error)
	// consumer API
	NextBlocks(context.Context, *NextBlocksRequest) (*NextBlocksReply, error)
	CommitBlock(context.Context, *CommitRequest) (*CommitReply, error)
	NewConsumer(context.Context, *NewConsumerRequest) (*NewConsumerReply, error)
	mustEmbedUnimplementedExtractorServer()
}

// UnimplementedExtractorServer must be embedded to have forward compatible implementations.
type UnimplementedExtractorServer struct {
}

func (UnimplementedExtractorServer) GetLatestBalance(context.Context, *GetLatestBalanceRequest) (*GetLatestBalanceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestBalance not implemented")
}
func (UnimplementedExtractorServer) GetTransactionByHash(context.Context, *GetTransactionByHashRequest) (*GetTransactionByHashReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionByHash not implemented")
}
func (UnimplementedExtractorServer) GetTransactionByHashFast(context.Context, *GetTransactionByHashRequest) (*GetTransactionByHashReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactionByHashFast not implemented")
}
func (UnimplementedExtractorServer) GetBlockByHeight(context.Context, *GetBlockByHeightRequest) (*GetBlockByHeightReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockByHeight not implemented")
}
func (UnimplementedExtractorServer) GetBlockHeaderByHeight(context.Context, *GetBlockByHeightRequest) (*GetBlockByHeightReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockHeaderByHeight not implemented")
}
func (UnimplementedExtractorServer) GetExtractors(context.Context, *GetExtractorsRequest) (*ExtractorConfigs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExtractors not implemented")
}
func (UnimplementedExtractorServer) UpdateExtractors(context.Context, *UpdateExtractorsRequest) (*ExtractorConfigs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateExtractors not implemented")
}
func (UnimplementedExtractorServer) DeleteExtractors(context.Context, *DeleteExtractorsRequest) (*ExtractorConfigs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteExtractors not implemented")
}
func (UnimplementedExtractorServer) NextBlocks(context.Context, *NextBlocksRequest) (*NextBlocksReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NextBlocks not implemented")
}
func (UnimplementedExtractorServer) CommitBlock(context.Context, *CommitRequest) (*CommitReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitBlock not implemented")
}
func (UnimplementedExtractorServer) NewConsumer(context.Context, *NewConsumerRequest) (*NewConsumerReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewConsumer not implemented")
}
func (UnimplementedExtractorServer) mustEmbedUnimplementedExtractorServer() {}

// UnsafeExtractorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExtractorServer will
// result in compilation errors.
type UnsafeExtractorServer interface {
	mustEmbedUnimplementedExtractorServer()
}

func RegisterExtractorServer(s grpc.ServiceRegistrar, srv ExtractorServer) {
	s.RegisterService(&Extractor_ServiceDesc, srv)
}

func _Extractor_GetLatestBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).GetLatestBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/GetLatestBalance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).GetLatestBalance(ctx, req.(*GetLatestBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_GetTransactionByHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).GetTransactionByHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/GetTransactionByHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).GetTransactionByHash(ctx, req.(*GetTransactionByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_GetTransactionByHashFast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionByHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).GetTransactionByHashFast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/GetTransactionByHashFast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).GetTransactionByHashFast(ctx, req.(*GetTransactionByHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_GetBlockByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).GetBlockByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/GetBlockByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).GetBlockByHeight(ctx, req.(*GetBlockByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_GetBlockHeaderByHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockByHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).GetBlockHeaderByHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/GetBlockHeaderByHeight",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).GetBlockHeaderByHeight(ctx, req.(*GetBlockByHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_GetExtractors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExtractorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).GetExtractors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/GetExtractors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).GetExtractors(ctx, req.(*GetExtractorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_UpdateExtractors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateExtractorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).UpdateExtractors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/UpdateExtractors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).UpdateExtractors(ctx, req.(*UpdateExtractorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_DeleteExtractors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteExtractorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).DeleteExtractors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/DeleteExtractors",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).DeleteExtractors(ctx, req.(*DeleteExtractorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_NextBlocks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NextBlocksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).NextBlocks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/NextBlocks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).NextBlocks(ctx, req.(*NextBlocksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_CommitBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).CommitBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/CommitBlock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).CommitBlock(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Extractor_NewConsumer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewConsumerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExtractorServer).NewConsumer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.ankrscan.extractor.Extractor/NewConsumer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExtractorServer).NewConsumer(ctx, req.(*NewConsumerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Extractor_ServiceDesc is the grpc.ServiceDesc for Extractor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Extractor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "com.ankrscan.extractor.Extractor",
	HandlerType: (*ExtractorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestBalance",
			Handler:    _Extractor_GetLatestBalance_Handler,
		},
		{
			MethodName: "GetTransactionByHash",
			Handler:    _Extractor_GetTransactionByHash_Handler,
		},
		{
			MethodName: "GetTransactionByHashFast",
			Handler:    _Extractor_GetTransactionByHashFast_Handler,
		},
		{
			MethodName: "GetBlockByHeight",
			Handler:    _Extractor_GetBlockByHeight_Handler,
		},
		{
			MethodName: "GetBlockHeaderByHeight",
			Handler:    _Extractor_GetBlockHeaderByHeight_Handler,
		},
		{
			MethodName: "GetExtractors",
			Handler:    _Extractor_GetExtractors_Handler,
		},
		{
			MethodName: "UpdateExtractors",
			Handler:    _Extractor_UpdateExtractors_Handler,
		},
		{
			MethodName: "DeleteExtractors",
			Handler:    _Extractor_DeleteExtractors_Handler,
		},
		{
			MethodName: "NextBlocks",
			Handler:    _Extractor_NextBlocks_Handler,
		},
		{
			MethodName: "CommitBlock",
			Handler:    _Extractor_CommitBlock_Handler,
		},
		{
			MethodName: "NewConsumer",
			Handler:    _Extractor_NewConsumer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "extractor.proto",
}
