// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: namespace.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type FoundationDbNamespace int32

const (
	//
	//stores blocks and transactions bodies.
	//keys: Blockchain-BlockHeight-BlockHash for blocks and Blockchain-BlockHeight-BlockHash-TransactionIndex for transactions
	//values: proto.Block (contains block headers with transactions)
	FoundationDbNamespace_BlocksNamespace FoundationDbNamespace = 0
	//
	//keys: Blockchain-TransactionHash
	//values: keys of transactions in StorageNamespace
	FoundationDbNamespace_TxByHash FoundationDbNamespace = 1
	//
	//keys: Blockchain-BlockHash
	//values: keys of blocks in StorageNamespace
	FoundationDbNamespace_BlockByHash FoundationDbNamespace = 2
	//
	//keys: Blockchain-BlockHeight
	//values: keys of blocks in StorageNamespace
	FoundationDbNamespace_BlockByNumber FoundationDbNamespace = 3
	//
	//stores blocks of canonical chain
	//keys: Blockchain-BlockHeight
	//values: keys of blocks in StorageNamespace
	FoundationDbNamespace_CanonicalChain FoundationDbNamespace = 4
	//
	//stores extractors configs
	//keys: extractor ID
	//values: proto.ExtractorConfig
	FoundationDbNamespace_ExtractorConfig FoundationDbNamespace = 5
	//
	//stores consumers offsets
	//keys: consumer ID
	//values: committed block height
	FoundationDbNamespace_ConsumerOffset FoundationDbNamespace = 6
	//
	//stores the latest block header of canonical chain
	//keys: Blockchain
	//values: proto.BlockHeader
	FoundationDbNamespace_LatestBlock FoundationDbNamespace = 7
)

// Enum value maps for FoundationDbNamespace.
var (
	FoundationDbNamespace_name = map[int32]string{
		0: "BlocksNamespace",
		1: "TxByHash",
		2: "BlockByHash",
		3: "BlockByNumber",
		4: "CanonicalChain",
		5: "ExtractorConfig",
		6: "ConsumerOffset",
		7: "LatestBlock",
	}
	FoundationDbNamespace_value = map[string]int32{
		"BlocksNamespace": 0,
		"TxByHash":        1,
		"BlockByHash":     2,
		"BlockByNumber":   3,
		"CanonicalChain":  4,
		"ExtractorConfig": 5,
		"ConsumerOffset":  6,
		"LatestBlock":     7,
	}
)

func (x FoundationDbNamespace) Enum() *FoundationDbNamespace {
	p := new(FoundationDbNamespace)
	*p = x
	return p
}

func (x FoundationDbNamespace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FoundationDbNamespace) Descriptor() protoreflect.EnumDescriptor {
	return file_namespace_proto_enumTypes[0].Descriptor()
}

func (FoundationDbNamespace) Type() protoreflect.EnumType {
	return &file_namespace_proto_enumTypes[0]
}

func (x FoundationDbNamespace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FoundationDbNamespace.Descriptor instead.
func (FoundationDbNamespace) EnumDescriptor() ([]byte, []int) {
	return file_namespace_proto_rawDescGZIP(), []int{0}
}

var File_namespace_proto protoreflect.FileDescriptor

var file_namespace_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x16, 0x63, 0x6f, 0x6d, 0x2e, 0x61, 0x6e, 0x6b, 0x72, 0x73, 0x63, 0x61, 0x6e, 0x2e,
	0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2a, 0xac, 0x01, 0x0a, 0x15, 0x46, 0x6f,
	0x75, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x13, 0x0a, 0x0f, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x78, 0x42, 0x79,
	0x48, 0x61, 0x73, 0x68, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x42, 0x79, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x61,
	0x6e, 0x6f, 0x6e, 0x69, 0x63, 0x61, 0x6c, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x10, 0x04, 0x12, 0x13,
	0x0a, 0x0f, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x4f,
	0x66, 0x66, 0x73, 0x65, 0x74, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x4c, 0x61, 0x74, 0x65, 0x73,
	0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x07, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_namespace_proto_rawDescOnce sync.Once
	file_namespace_proto_rawDescData = file_namespace_proto_rawDesc
)

func file_namespace_proto_rawDescGZIP() []byte {
	file_namespace_proto_rawDescOnce.Do(func() {
		file_namespace_proto_rawDescData = protoimpl.X.CompressGZIP(file_namespace_proto_rawDescData)
	})
	return file_namespace_proto_rawDescData
}

var file_namespace_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_namespace_proto_goTypes = []interface{}{
	(FoundationDbNamespace)(0), // 0: com.ankrscan.namespace.FoundationDbNamespace
}
var file_namespace_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_namespace_proto_init() }
func file_namespace_proto_init() {
	if File_namespace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_namespace_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_namespace_proto_goTypes,
		DependencyIndexes: file_namespace_proto_depIdxs,
		EnumInfos:         file_namespace_proto_enumTypes,
	}.Build()
	File_namespace_proto = out.File
	file_namespace_proto_rawDesc = nil
	file_namespace_proto_goTypes = nil
	file_namespace_proto_depIdxs = nil
}
